# DEFINITIONS

## Definitions.

As used in this Agreement, the following terms shall have the following meanings:

1. "Active List" means the list of players, maintained by the NBA, who have signed Player Contracts with a Team and are otherwise eligible to participate in a Regular Season game.
2. "Agreement" means this Collective Bargaining Agreement entered into as of July 29, 2005.
3. "Audit Report" or "final Audit Report" means the audit report prepared in accordance with Article VII, Section 10.
4. "Average Player Salary" means, with respect to any Salary Cap Year, Total Salaries divided by an amount equal to the product of the number of Teams in the NBA (other than Expansion Teams during their first two (2) Salary Cap Years) multiplied by 13.2.
5. "Base Compensation" means the component of Compensation other than bonuses of any kind.
6. "Base Year Compensation" means an amount used to calculate the Exception that results from the trade of certain Player Contracts, as determined in accordance with Article VII, Section 6(h)(4).
7. "Basketball Related Income" or "BRI" means basketball related income as defined in Article VII, Section 1(a) and (b).
8. "Benefits" or "Total Benefits" means the sum of all amounts paid or to be paid on an accrual basis during any Salary Cap Year by the NBA or NBA Teams, other than Expansion Teams during their first two Salary Cap Years, for the specific benefits set forth in Article IV.
9. "Commissioner" means the Commissioner of the NBA.
10. "Compensation" means the compensation that is or could be earned by, or is paid or payable to, an NBA player (including players whose Player Contracts have been terminated) in accordance with a Player Contract (whether such payment is sent to the player directly or to a person or entity designated by a player).
11. "Contract" (see "Uniform Player Contract").
12. "Current Base Compensation" means the component of Base Compensation other than Deferred Base Compensation.
13. "Current Compensation" means the component of Compensation other than Deferred Compensation.
14. "Deferred Base Compensation" means the component of Deferred Compensation other than bonuses of any kind.
15. "Deferred Compensation" means the component of Compensation payable to a player during the period commencing after the term covered by the Player Contract, in accordance with the rules set forth in Article VII. The determination of whether Compensation is Deferred Compensation will be based upon the time set by the Player Contract for the player to receive the Compensation, without regard to whether the obligation is funded currently or secured in any fashion.
16. "Draft" or "NBA Draft" means the NBA's annual draft of Rookie basketball players.
17. "Early Qualifying Veteran Free Agent" means a Veteran Free Agent who, prior to becoming a Veteran Free Agent, played under one or more Player Contracts covering some or all of each of the two (2) preceding Seasons, and who either exclusively played with his Prior Team during such two Seasons, or, if he played for more than one Team during such period, changed Teams only (i) by means of trade, or (ii) by signing with his Prior Team during the first of the two (2) Seasons.
18. "Early Termination Option" (or "ETO") means an option in favor of a player to shorten the stated number of years covered by a Player Contract in accordance with Article XII.
19. "Effective Season" means, with respect to an Early Termination Option, the first Season covered by the Early Termination Option. (For example, if a Contract were to contain an Early Termination Option exercisable following the 2009-2010 Season, the Effective Season would be the 2010-11 Season.)
20. "Estimated Average Player Salary" means, for a particular Salary Cap Year, 108\% of the prior Salary Cap Year's Average Player Salary.
21. "Exception" means an exception to the rule that a Team's Team Salary may not exceed the Salary Cap.
22. "Expansion Team" means the Charlotte Bobcats and any other Team that becomes a member of the NBA through expansion following the date of this Agreement and commences play during the term of this Agreement.
23. "Extension" means an amendment to a Player Contract lengthening the term of the Contract for a specified period of years.
24. "First Round Pick" means a player selected by a Team in the first round of the Draft.
25. "Free Agent" means: (i) a Veteran Free Agent; (ii) a Rookie Free Agent; (iii) a Veteran whose Player Contract has been terminated in accordance with the NBA waiver procedure; or (iv) a player whose last Player Contract was a 10-Day Contract and who either completed the Contract by rendering the playing services called for thereunder or was released early from such Contract.
26. "Generally Recognized League Honors" means the following NBA league honors awarded to players: NBA Most Valuable Player; NBA Finals Most Valuable Player; NBA Defensive Player of the Year; NBA Sixth Man Award; NBA Most Improved Player; All-NBA Team (First, Second, or Third); NBA All-Defensive Team (First or Second); and All-Star Team Selection.
27. "Inactive List" means the list of players, maintained by the NBA, who have signed Player Contracts with a Team and are otherwise ineligible to participate in a Regular Season game.
28. "Incentive Compensation" means the component of Compensation consisting of one or more bonuses described in Article II, Sections 3(b)(iii) and (iv) and 3(c).
29. "Likely Bonus" means Incentive Compensation included in a player's Salary in accordance with Article VII, Section 3(d).
30. "Member" or "Team" means any team that is a member of the NBA.
31. "Minimum Annual Salary" means the minimum Salary that must be included in a Player Contract that covers the entire Regular Season in accordance with Article II, Section 6(a).
32. "Minimum Annual Salary Scale" means the scale annexed hereto as Exhibit C.
33. "Minimum Player Salary" means: (i) with respect to a Contract that covers the entire Regular Season, the Minimum Annual Salary called for under Article II, Section 6(a); (ii) with respect to a Rest-of-Season Contract, the Minimum Annual Salary called for under Article II, Section 6(a) multiplied by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season as of the date such Rest-of-Season Contract is entered into, and the denominator of which is the total number of days of that NBA Regular Season; and (iii) with respect to a 10-Day Contract, the Minimum Annual Salary called for under Article II, Section 6(a) multiplied by a fraction, the numerator of which is the number of days covered by the Contract and the denominator of which is the total number of days of that NBA Regular Season.
34. "Minimum Team Salary" means the minimum amount in Salary obligations to, or on behalf of, players with respect to an NBA Season that each Team must incur or pay.
35. "Moratorium Period" means:
    (i) With respect to the 2006-07 Salary Cap Year, the period July 1, 2006 through July 11, 2006.
    (ii) With respect to the 2007-08 Salary Cap Year, the period July 1, 2007 through July 10, 2007.
    (iii) With respect to the 2008-09 Salary Cap Year, the period July 1, 2008 through July 8, 2008.
    (iv) With respect to the 2009-10 Salary Cap Year, the period July 1, 2009 through July 7, 2009.
    (v) With respect to the 2010-11 Salary Cap Year, the period July 1, 2010 through July 7, 2010.
    (vi) With respect to the 2011-12 Salary Cap Year (if the NBA exercises its option to extend this Agreement pursuant to Article XXXIX), the period July 1, 2011 through July 7, 2011.
36. The term "negotiate" means, with respect to a player or his representatives on the one hand, and a Team or its representatives on the other hand, to engage in any written or oral communication relating to the possible employment, or terms of employment, of such player by such Team as a basketball player, regardless of who initiates such communication.
37. "Non-Qualifying Veteran Free Agent" means a Veteran Free Agent who is not a Qualifying Veteran Free Agent or an Early Qualifying Veteran Free Agent.
38. "Option" means an option in a Player Contract in favor of a Team or player to extend such Contract beyond its stated term.
39. "Option Buy-Out Amount" means any amount payable to a player in connection with either the exercise of an Early Termination Option or the non-exercise of an Option.
40. "Option Year" means the year that would be added to a Player Contract if an Option were exercised.
41. "Performance Bonus" means any Incentive Compensation described in Article II, Section 3(b)(iii).
42. "Player Contract" (see "Uniform Player Contract").
43. "Prior Team" means the Team for which a player was last under Contract prior to becoming a Qualifying Veteran Free Agent, Early Qualifying Veteran Free Agent or a Non-Qualifying Veteran Free Agent.
44. "Qualifying Offer" means an offer of a Uniform Player Contract, signed by the Team, that: (i) is either personally delivered to the player or his representative or sent by pre-paid certified, registered or overnight mail to the last known address of the player or his representative; (ii) is for a period of one year; and (iii) provides for: (A) for First Round Picks finishing their Rookie Scale Contracts, Salary (excluding Incentive Compensation), Likely Bonuses and Unlikely Bonuses equal to the Salary (excluding Incentive Compensation), Likely Bonuses and Unlikely Bonuses, respectively, provided in the fourth Salary Cap Year of the Rookie Scale Contract increased by the percentage called for in Exhibit B hereto; and (B) for all other players subject to a Right of First Refusal in accordance with Article XI, the greater of (x) 125\% of the player's Salary (excluding Incentive Compensation), Likely Bonuses and Unlikely Bonuses, respectively, for the last Salary Cap Year covered by the player's prior Contract, or (y) Base Compensation equal to the sum of the Minimum Annual Salary applicable to the player (for the Season covered by the Qualifying Offer) plus \$175,000 (with no bonuses of any kind). All other terms and conditions in the Qualifying Offer must be unchanged from those that applied to the last year of the player's prior Contract (including, but not limited to, the percentage of Base Compensation that is protected), provided that such terms and conditions are allowable amendments under this Agreement at the time the Qualifying Offer is made. In addition, a Team shall be permitted to include in any Qualifying Offer an Exhibit 6 to the UPC requiring that the player, if he signs the Qualifying Offer, pass a physical examination to be performed by a physician designated by the Team as a condition precedent to the validity of the Contract.
45. "Qualifying Veteran Free Agent" means a Veteran Free Agent who, prior to becoming a Veteran Free Agent, played under one or more Player Contracts covering some or all of each of the three preceding Seasons and either played exclusively with his Prior Team during such three Seasons, or, if he played with more than one Team during such period, changed Teams only (i) by means of trade, or (ii) by signing with his Prior Team during the first of the three Seasons.
46. "Regular Salary" means a player's Salary, less any component thereof that is a signing bonus (or deemed a signing bonus in accordance with Article VII) and any component thereof that is Incentive Compensation.
47. "Regular Season" means, with respect to any Season, the period beginning on the first day and ending on the last day of regularly scheduled (as opposed to exhibition or playoff) competition between NBA Teams.
48. "Renegotiation," "renegotiate," or "renegotiated" means a Contract amendment that provides for an increase in Salary and/or Unlikely Bonuses.
49. "Replacement Player" means, where appropriate, either a player who is acquired by a Team pursuant to the Traded Player Exception, or a player who is signed or acquired by a Team pursuant to the Disabled Player Exception.
50. "Required Tender" means an offer of a Uniform Player Contract to a Draft Rookie, signed by the Team, that: (i) is either personally delivered to the player or his representative or sent by pre-paid certified, registered, or overnight mail to the last known address of the player or his representative; (ii) with respect to a First Round Pick, (A) affords the player until at least the first day of the following Regular Season to accept, and (B) satisfies the requirements of a Rookie Scale Contract set forth in Article VIII, Section 1 or 2; and (iii) with respect to a Second Round Pick, (A) affords the player until at least the immediately following October 15 to accept, (B) has a stated term of one (1) Season, and (C) calls for at least the Minimum Annual Salary then applicable to the player. In addition, a Team shall be permitted to include in any Required Tender an Exhibit 6 to the UPC requiring that the player, if he signs the Required Tender, pass a physical examination to be performed by a physician designated by the Team as a condition precedent to the validity of the Contract.
51. "Restricted Free Agent" means a Veteran Free Agent who is subject to a Team's right of first refusal in accordance with Article XI.
52. "Rookie" means a person who has never signed a Player Contract with an NBA Team.
    (i) "Draft Rookie" means a Rookie who is selected in the NBA Draft.
    (ii) "Non-Draft Rookie" means a Rookie who is not selected in the NBA Draft for which he is first eligible.
53. "Rookie Free Agent" means: (i) a Draft Rookie who, pursuant to the provisions of Article VIII, Section 3 or Article X, is no longer subject to the exclusive negotiating rights of any Team, and who may be signed by any Team; or (ii) a Non-Draft Rookie.
54. "Rookie Salary Scales" means the tables annexed hereto as Exhibit B.
55. "Rookie Scale Amounts" means the amounts set forth in the tables annexed hereto as Exhibit B.
56. "Rookie Scale Contract" means the initial Uniform Player Contract entered into, in accordance with Article VIII, Section 1 or 2, between a First Round Pick and the Team that holds his draft rights.
57. "Room" means the extent to which: (i) a Team's then-current Team Salary is less than the Salary Cap; or (ii) a Team is entitled to use one of the Salary Cap Exceptions set forth in Article VII, Section 6(c), (d), (e) and (h) (Disabled Player, Bi-annual, Mid-Level Salary and Traded Player Exceptions).
58. "Salary" means, with respect to a Salary Cap Year, a player's Compensation with respect to the Season covered by such Salary Cap Year, plus any other amount that is deemed to constitute Salary in accordance with the terms of this Agreement, not including Unlikely Bonuses, any benefits the player received in accordance with the terms of this Agreement (including, e.g., the benefits provided for by Article IV, per diem, and moving expenses), and any portion of the player's Compensation that is attributable to another Salary Cap Year inaccordance with this Agreement. Salary also includes any consideration received by a retired player that is deemed to constitute Salary in accordance with the terms of Article XIII.
59. "Salary Cap" means the maximum allowable Team Salary for each Team for a Salary Cap Year, subject to the rules and exceptions set forth in this Agreement.
60. "Salary Cap Year" means the period from July 1 through the following June 30.
61. "Season" or "NBA Season" means the period beginning on the first day of training camp and ending immediately after the last game of the NBA Finals.
62. "Second Round Pick" means a player selected by a Team in the second round of the Draft.
63. "Team" or "NBA Team" (see "Member").
64. "Team Affiliate" means:
    (i) any individual or entity who or which (directly or indirectly) holds an ownership interest in a Team (other than ownership of publicly-traded securities constituting less than 5\% of the ownership interests in a Team);
    (ii) any individual or entity who or which (directly or indirectly) controls, is controlled by or is under common control with, or who or which is an entity affiliated with or an individual related to, a Team;
    (iii) any individual or entity who or which (directly or indirectly) controls, is controlled by or is under common control with, or who or which is an entity affiliated with or an individual related to, an individual or entity described in Section 1 (zzz)(i) or (ii) above; or
    (iv) any entity in which 10\% or more of the ownership interests are held (directly or indirectly) by an individual or entity who or which holds (directly or indirectly) 10\% or more of the ownership interests in a Team or in an entity described in Section 1(zzz)(ii) above.
    
    For the purposes of this Section 1(lll): an individual shall only be deemed to be "related to" a Team or another individual or entity if such individual is an officer, director or executive employee of such Team or entity, or is a member of such individual's immediate family; and "controls" or "is controlled by" shall include (without limitation) the circumstance in which an individual or a Team or entity has or can exercise effective control.
65. "Team Salary" means, with respect to a Salary Cap Year, the sum of all Salaries attributable to a Team's active and former players plus other amounts as computed in accordance with Article VII, less applicable credit amounts as computed in accordance with Article VII.
66. "Total Salaries" means the total Salaries included in the Team Salary of all NBA Teams for or with respect to a Salary Cap Year in accordance with this Agreement, other than the Salaries included in the Team Salary of Expansion Teams during their first two Salary Cap Years, as determined in accordance with Article VII. For purposes of this definition: (i) Total Salaries shall include all Incentive Compensation excluded from Salaries in accordance with Article VII, Section 3(d) but actually earned by NBA players during such Salary Cap Year, and shall exclude all Incentive Compensation included in Salaries in accordance with Article VII,Section 3(d) but not actually earned by NBA players during such Salary Cap Year; (ii) Total Salaries shall include any amounts paid by the NBA to the Players Association for distribution to NBA players pursuant to Article XXIX, Section 3(c); (iii) Total Salaries shall include the aggregate Salaries, if any, that are excluded from Team Salaries pursuant to Article VII, Section 4(h); and (iv) Total Salaries shall include any consideration received by a retired player that is included in Team Salary in accordance with the terms of Article XIII.
67. "Total Salaries and Benefits" means the sum of Total Salaries plus Total Benefits.
68."Traded Player" means a player whose Player Contract is assigned by one Team to another Team other than by means of the NBA waiver procedure.
69. "Uniform Player Contract" or "Player Contract" or "Contract" means the standard form of written agreement between a person and a Team required for use in the NBA by Article II, pursuant to which such person is employed by such Team as a professional basketball player.
70. "Unlikely Bonus" means Incentive Compensation excluded from a player's Salary in accordance with Article VII, Section 3(d).
71. "Unrestricted Free Agent" means a Free Agent who is not subject to a Team's right of first refusal.
72. "Veteran" or "Veteran Player" means a person who has signed at least one Player Contract with an NBA Team.
73. "Veteran Free Agent" means a Veteran who completed his Player Contract (other than a 10-Day Contract) by rendering the playing services called for thereunder.
74. "Years of Service" means the number of years of NBA service credited to a player in accordance with the following: a player will be credited with one (1) year of NBA service for each year that he is on an NBA Active List or Inactive List for one (1) or more days during the Regular Season. Notwithstanding the above, a player will not receive credit for a Year of Service for any year in which he: (i) withholds playing services called for by a Player Contract or this Agreement for more than thirty (30) days after the Season begins, or (ii) is a Restricted Free Agent, has been tendered a Qualifying Offer by his Prior Team that has been expressly left open by that Team until at least March 1, and has not signed a Player Contract with any Team by March 1. In addition, notwithstanding the above, a player will not receive credit for a Year of Service for being on an NBA Active List or Inactive List as a result of signing a Player Contract that is disapproved by the Commissioner. In no event can a player be credited with more than one (1) Year of Service with respect to any one NBA Season. A Year of Service will be credited to a player on the June 30 following the Season with respect to which it is being credited. Under no circumstances shall the definition of Years of Service herein be used for purposes of determining a player's years of credited service under the NBA Players' Pension Plan. Players shall be credited with Years of Service pursuant to this Section 1(vvv) only in respect of Seasons covered by this Agreement. Years of Service credit for prior Seasons shall be determined in accordance with the provisions of the 1999 NBA/NBPA Collective Bargaining Agreement.