# LENGTH OF PLAYER CONTRACTS

## Maximum Term.

Except where a shorter term is expressly provided for elsewhere in this Agreement, a Player Contract entered into after the date of this Agreement may cover, in the aggregate, up to but no more than five (5) Seasons (including any Season covered by an Option) from the date such Contract is signed; provided, however, that (a) a Player Contract between a Qualifying Veteran Free Agent and his Prior Team may cover, in the aggregate, up to but no more than six (6) Seasons (including any Season covered by an Option) from the date such Contract is signed, and (b) an Extension of a Rookie Scale Contract may cover, in the aggregate, up to but no more than six (6) Seasons (including any Season covered by an Option) from the date such extension is signed.

## Computation of Time.

For purposes of Section 1 above, if a Player Contract or Extension is signed after the beginning of a Season, the Season in which the Contract or Extension is signed shall be counted as one (1) full Season covered by the Contract or Extension.