# LIMITATION ON DEFERRED COMPENSATION

## General Limitation.

No NBA Team may sign a Player Contract with any player under which more than 30\% of Compensation is Deferred Compensation. For purposes of this provision only, Deferred Compensation shall mean Deferred Compensation during the period commencing more than two (2) years after the playing term covered by a Player Contract.

## Attribution.

All Player Contracts shall specify the Season(s) to which any Deferred Compensation is attributable.

## Rabbi Trusts.

(a) Notwithstanding Section 1, a Player Contract may provide for an annuity to be purchased by the Team that will pay the Player (or his designees) an amount of Deferred Compensation in excess of 30\% of Compensation, provided that:
    (i) The Team and the Player agree with respect to the form and terms of the annuity instrument and the institution from which it is purchased;
    (ii) Ownership of the annuity and all related aspects are structured in a manner that qualifies the arrangement as a tax deferred ("rabbi") trust, in the opinion of the NBA's tax advisor; and
    (iii) The total cost of the annuity and the schedule of payment of such costs are specified in the Player Contract.
(b) Notwithstanding anything to the contrary contained in Section 3(a) above:
    (i) If the institution obligated to make payment under the annuity fails to do so for any reason (other than non-compliance by the Team with the provisions of the annuity contract), the Team shall thereupon become obligated to pay to the Player as Deferred Compensation an amount, if any, equal to the unpaid portion of the purchase price of the annuity for which the Team remains obligated; and
    (ii) If the creditors of the Team and not the Player receive payments under the annuity, the Team shall thereupon become obligated to pay to the Player as Deferred Compensation an amount equal to the full purchase price of the annuity.