# 

## AUTHORIZATION FOR TESTING

|        |                     |
| :----- | :-----------------: |
| To:    | ___________________ |
|        |                     |
| Player | ___________________ |

Please be advised that on __________________________, you were the subject of a meeting or conference call held pursuant to the Anti-Drug Program set forth in Article XXXIII of the Collective Bargaining Agreement between the NBA and the National Basketball Players Association, dated July 29, 2005 (the "Agreement"). Following the meeting or conference call, I authorized the NBA to conduct the testing procedures set forth in the Agreement, and you are hereby directed to submit to those testing procedures, on demand, no more than four times during the next six weeks.

Please be advised that your failure to submit to these procedures may result in substantial penalties, including but not limited to your dismissal and disqualification from the NBA.

|                          |
| :----------------------- |
| ________________________ |
| Independent Expert       |
| Dated:                   |
| ________________________ |

## PROHIBITED SUBSTANCES

(a) Drugs of Abuse

- Amphetamine and its analogs (including but not limited to methamphetamine and MDMA)
- Cocaine
- LSD
- Opiates (Heroin, Codeine, Morphine)
- Phencyclidine ("PCP")

(b) Marijuana and its by-products

(c) Steroids, Performance Enhancing Drugs, and Masking Agents (SPEDs)

- Amiphenazole
- Androstanediol
- Androstanedione
- Androstenediol
- Androstenedione
- Bolasterone
- Boldenone
- Boldione
- Bromantan
- Calusterone
- Clenbuterol
- Clobenzorex
- Clomiphene
- Clostebol
- Cyclofenil
- Danazol
- Dehydrochlormethyltestosterone
- Dehydroepiandrosterone (DHEA)
- Desoxymethyltestosterone (DMT)
- Dihydrotestosterone
- 4-dihydrotestosterone
- Dromostanolone
- Drostanolone
- 18a-homo-17b-hydroxyestr-4-en-3-one
- Ephedra (also called Ma Huang, Bishop's Tea and Chi Powder)
- Ephedrine
- Epitestosterone
- 13a-ethyl-17a-hydroxygon-4-en-one
- Etilefrine
- Ethylestrenol
- Fenethylline
- Fenfluramine
- Fluoxymesterone
- Formebolone
- Fulvestrant
- Furazabol
- Gestrinone
- Human Chorionic Gonadotropin
- Human Growth Hormone
- 4-hydroxytestosterone
- Mestanolone
- Mesterolone
- Methandienone
- Methandriol
- Methenolone
- Methyldienolone
- 17a-methyl-3b, 17b-dihydroxy-5a-androstane
- 17a-methyl-3a, 17b-dihydroxy-5a-androstane
- 17a-methyl-3b, 17b-dihydroxyandrost-4-ene
- 17a-methyl-1-dihydrotestosterone
- 17a-methyl-4a-hydroxynandrolone
- Methylephedrine
- Methylphenidate
- Methyltestosterone
- Methyltrienolone
- Mibolerone
- Modafinil
- Nandrolone (also called 19-nortestosterone)
- Nikethamide
- 19-norandrostenediol
- 19-norandrostendione
- Norbolethone
- Norclostebol
- Norethandrolone
- Norfenfluramine
- Normethandrolone
- Norpseudoephedrine (also called cathine)
- Oxabolone (also called 4-hydroxy-19-nortestosterone)
- Oxandrolone
- Oxymesterone
- Oxymetholone
- Pemoline
- Phenmetrazine
- Phentermine
- Phenylpropanolamine (PPA)
- Probenecid
- Pseudoephedrine
- Quinbolone
- Stanozolol
- Stenbolone
- Strychnine
- Testolactone
- Testosterone
- Tetrahydrogestrinone (THG)
- Trenbolone
- Zeranol
- Zilpaterol

(d) Diuretics

- Acetazolamide
- Amiloride
- Bendroflumethiazide
- Benzthiazide
- Bumetanide
- Canrenone
- Chlorothiazide
- Chlorthalidone
- Clopamide
- Cyclothiazide
- Dichlorphenamide
- Ethacrynic Acid
- Flumethiazide
- Furosemide
- Hydrochlorothiazide
- Hydroflumethiazide
- Indapamide
- Methylclothiazide
- Metolazone
- Polythiazide
- Quinethazone
- Spironolactone
- Triamterene
- Trichlormethiazide


## COLLECTION PROCEDURES

When the player arrives at the collection site, the collector will ensure that the player is positively identified through presentation of photo ID or identification by a team representative. If the player's identity cannot be established, the collector shall not proceed with the collection.

The player will be asked to select a sealed urine specimen cup. The player will then provide his urine specimen under the direct observation of the collector.

The collector shall ensure that the player has provided a urine specimen of sufficient volume for accurate testing. If such a sample cannot immediately be provided by the player, he shall be instructed to remain at the testing site for a reasonable period of time until he can provide such a specimen. Once the specimen has been obtained, the player will select a sealed specimen kit, which contains two bottles. The collector, in the presence of the player, will pour the specimen into two bottles. One bottle will be used as the primary or "A" specimen and the other will be used as the split or "B" specimen. The specimen bottles will be sealed with tamper-proof seals in the presence of the player. The seals will contain a unique identification number that corresponds to the number on the chain of custody form.

The player and collector will complete the chain of custody form that documents the handling of the specimen. The collector will note any irregularities concerning the specimen on the chain of custody form. Both the player and collector will sign the chain of custody form. The chain of custody form along with the two specimen bottles will be placed back into the kit. The kit will be sealed and sent via overnight courier to the laboratory for testing.

Once the specimen arrives at the laboratory, the primary specimen will be analyzed. If the primary specimen tests positive, the split sample will be placed in frozen storage and will be available for testing by a different laboratory, if requested by the player.

## STEROIDS, PERFORMANCE-ENHANCING DRUGS AND MASKING AGENTS CONFIRMATORY LABORATORY ANALYSIS LEVELS

All SPEDs, except those listed below, at any detectable level.

Ephedra/Ephedrine                            10 mcg/ml
Methylephedrine                              10 mcg/ml
Nandrolone                                   2 ng/ml
Norpseudoephedrine                           5 mcg/ml
Phenylpropanolamine (PPA)                    25 mcg/ml
Pseudoephedrine                              25 mcg/ml
Testosterone                                 4:1 t/e ratio
